# Generated by Django 4.2.2 on 2023-07-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylistapp', '0002_grocerylistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitemmodel',
            name='list_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
