# Generated by Django 4.2.2 on 2023-07-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylistapp', '0003_groceryitemmodel_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitemmodel',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerylistapp.grocerylistmodel'),
        ),
    ]
