services:
  backend:
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    
    build: ./api        
    ports:
      - "8000:8000"

    volumes:
      - ./api:/app/backend

  frontend:
    command: npm start

    build: ./app
    ports:
      - "3000:3000"

    volumes:
      - ./app:/app/frontend
      - /app/frontend/node_modules

    depends_on:
      - backend
